import { expect, test, type Page, type WebSocketRoute } from "@playwright/test";
import { denseNetworkProjection, networkProjection } from "./fixtures/network-data";

test.use({ actionTimeout: 10_000 });

async function openWorkspace(page: Page, initialFocusNodeId?: string, initialProjection = networkProjection()) {
  const sockets: WebSocketRoute[] = [];
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.routeWebSocket(/\/v1\/games\/network-test\/network\/stream/, (socket) => {
    sockets.push(socket);
    socket.send(JSON.stringify({ sequence: 12, resync: true, projection: initialProjection }));
  });
  await page.goto("/e2e/fixtures/network-workspace.html" + (initialFocusNodeId ? "?focus=" + encodeURIComponent(initialFocusNodeId) : ""));
  await expect(page.getByRole("status")).toHaveText("Live");
  if (!initialFocusNodeId) await expect(page.locator(".react-flow__node")).toHaveCount(initialProjection.nodes.length);
  return { sockets, errors };
}

test("searches and filters topology, then inspects directional failures and authorized messages", async ({ page }, testInfo) => {
  const { errors } = await openWorkspace(page);
  const summary = page.locator('[aria-label="Visible network summary"]');
  await page.getByRole("combobox", { name: "Domain", exact: true }).selectOption("Air");
  await expect(summary).toContainText("2 / 4 terminals");
  await expect(page.locator(".react-flow__edge")).toHaveCount(2);
  await page.getByLabel("Search terminals").fill("nobody");
  await expect(page.getByText("No terminals match your filters")).toBeVisible();
  await page.getByRole("button", { name: "Reset filters", exact: true }).click();
  await page.getByLabel("Link status").selectOption("queued");
  await expect(summary).toContainText("1 directional links");
  await expect(summary).toContainText("3 queued packets");
  await page.getByRole("button", { name: "Inspect Joint Command", exact: true }).click();
  await expect(page.getByRole("region", { name: "Terminal details" }).locator("dl > div").filter({ hasText: "Visible inbound" })).toHaveText(/Visible inbound\s*0/);
  await page.getByRole("button", { name: "Clear filters", exact: true }).click();
  await page.getByRole("button", { name: "Inspect Blue One", exact: true }).click();
  await expect(page.getByRole("region", { name: "Terminal details" })).toContainText("Receiver clear");
  await page.getByRole("button", { name: "Focus connections", exact: true }).click();
  await expect(summary).toContainText("3 / 4 terminals");
  await page.getByRole("button", { name: "Blue One → Blue Two Unavailable", exact: true }).click();
  const details = page.getByRole("region", { name: "Link details" });
  await expect(details).toContainText("0 bit/s");
  await expect(details).toContainText("100%");
  await page.getByRole("button", { name: "View messages on this link" }).click();
  await expect(page.locator(".network-message-list > button")).toHaveCount(1);
  await page.getByRole("button", { name: "Inspect message: Movement order blocked by receiver jamming", exact: true }).click();
  const message = page.getByRole("region", { name: "Message details" });
  await expect(message).toContainText("ReceiverInterference");
  await expect(message).toContainText("Not delivered");
  await expect(message).toContainText("simulation-controlled");
  await page.getByRole("button", { name: "Clear selection · show all messages", exact: true }).click();
  await page.getByLabel("Message state").selectOption("delivered");
  await expect(page.locator(".network-message-list > button")).toHaveCount(2);
  await page.getByLabel("Search messages").fill("joint command");
  await expect(page.locator(".network-message-list > button")).toHaveCount(1);
  await page.getByRole("button", { name: "Inspect message: Move north at 130 m/s", exact: true }).click();
  await expect(message).toContainText("120.0 ms");
  await page.screenshot({ path: testInfo.outputPath("network-message-inspector.png") });
  expect(errors).toEqual([]);
});

test("preserves dragged node positions and DOM nodes during live updates and filtering", async ({ page }, testInfo) => {
  const { sockets, errors } = await openWorkspace(page);
  const node = page.locator('.react-flow__node[data-id="blue-one"]');
  const box = await node.boundingBox();
  if (!box) throw new Error("Blue One node has no bounds");
  const originalStyle = await node.getAttribute("style");
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 70, box.y + box.height / 2 + 80, { steps: 8 });
  await page.mouse.up();
  const draggedStyle = await node.getAttribute("style");
  expect(draggedStyle).not.toBe(originalStyle);
  await node.evaluate((element) => element.setAttribute("data-retained", "yes"));
  const updated = networkProjection();
  updated.tick = 13;
  updated.nodes.reverse();
  updated.nodes.find((item) => item.id === "blue-one")!.receiver_jammed = true;
  updated.links[0].queued_packets = 7;
  sockets[0].send(JSON.stringify({ sequence: 13, resync: false, projection: updated }));
  await expect(page.getByText("TICK 13 · ROLE-VISIBLE TOPOLOGY", { exact: true })).toBeVisible();
  await expect(node.locator(".network-node-card")).toHaveClass(/jammed/);
  await expect(node).toHaveAttribute("data-retained", "yes");
  await expect(node).toHaveAttribute("style", draggedStyle!);
  await page.getByRole("combobox", { name: "Domain", exact: true }).selectOption("Sea");
  await expect(page.locator(".react-flow__node")).toHaveCount(1);
  await page.getByRole("combobox", { name: "Domain", exact: true }).selectOption("all");
  await expect(node).toHaveAttribute("style", draggedStyle!);
  await page.getByRole("button", { name: "Reset layout", exact: true }).click();
  await expect(node).not.toHaveAttribute("style", draggedStyle!);
  await page.screenshot({ path: testInfo.outputPath("network-workspace-desktop.png") });
  expect(errors).toEqual([]);
});

test("keeps topology visible through reconnects and malformed updates without accepting stale frames", async ({ page }) => {
  const { sockets, errors } = await openWorkspace(page);
  const stale = networkProjection();
  stale.tick = 11;
  sockets[0].send(JSON.stringify({ sequence: 11, resync: false, projection: stale }));
  await expect(page.getByText("TICK 12 · ROLE-VISIBLE TOPOLOGY", { exact: true })).toBeVisible();
  await sockets[0].close({ code: 1000, reason: "Test disconnect" });
  await expect(page.getByRole("status")).toHaveText("Reconnecting");
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await expect(page.getByRole("alert")).toContainText("last received topology");
  await expect.poll(() => sockets.length).toBe(2);
  expect(new URL(sockets[1].url()).searchParams.get("after_sequence")).toBe("12");
  await expect(page.getByRole("status")).toHaveText("Live");
  sockets[1].send("{not-json");
  await expect(page.getByRole("alert")).toContainText("unreadable network update");
  await expect(page.locator(".react-flow__node")).toHaveCount(4);
  await expect.poll(() => sockets.length).toBe(3);
  expect(new URL(sockets[2].url()).searchParams.has("after_sequence")).toBe(false);
  await expect(page.getByRole("status")).toHaveText("Live");
  await expect(page.getByRole("alert")).toHaveCount(0);
  expect(errors).toEqual([]);
});

test("shows graph and inspector together on a narrow screen and closes with Escape", async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const { errors } = await openWorkspace(page);
  await page.getByRole("button", { name: "Inspect Blue Two", exact: true }).click();
  await expect(page.getByRole("region", { name: "Terminal details" })).toContainText("Receiver jammed");
  const graph = await page.locator(".network-canvas").boundingBox();
  const inspector = await page.locator(".network-inspector").boundingBox();
  expect(graph?.height).toBeGreaterThanOrEqual(200);
  expect(inspector!.y).toBeGreaterThanOrEqual(graph!.y + graph!.height - 1);
  await expect.poll(() => page.getByRole("region", { name: "Terminal details" }).boundingBox().then((box) => box?.y ?? -1)).toBeGreaterThanOrEqual(inspector!.y);
  await expect.poll(() => page.locator('.react-flow__node[data-id="blue-two"]').boundingBox().then((box) => box?.width ?? 0)).toBeGreaterThanOrEqual(185);
  expect(await page.evaluate("document.documentElement.scrollWidth")).toBeLessThanOrEqual(390);
  await expect(page.getByRole("tab", { name: "Topology", exact: true })).toBeInViewport({ ratio: 0.99 });
  await page.screenshot({ path: testInfo.outputPath("network-workspace-mobile.png") });
  await page.keyboard.press("Escape");
  await expect(page.getByText("Returned to map", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test("filters a scenario-sized topology and retains filters across subsequent live snapshots", async ({ page }, testInfo) => {
  const { sockets, errors } = await openWorkspace(page);
  const dense = denseNetworkProjection();
  sockets[0].send(JSON.stringify({ sequence: 20, resync: true, projection: dense }));
  const summary = page.locator('[aria-label="Visible network summary"]');
  await expect(summary).toContainText("64 / 64 terminals");
  await expect(summary).toContainText("4032 directional links");
  await page.getByRole("combobox", { name: "Domain", exact: true }).selectOption("Air");
  await expect(summary).toContainText("16 / 64 terminals");
  await expect(page.locator(".react-flow__edge")).toHaveCount(240);
  await page.getByLabel("Link status").selectOption("queued");
  await expect(page.locator(".react-flow__edge")).toHaveCount(1);
  dense.tick = 21;
  dense.nodes.reverse();
  dense.links.find((link) => link.queued_packets > 0)!.queued_packets = 9;
  sockets[0].send(JSON.stringify({ sequence: 21, resync: false, projection: dense }));
  await expect(page.getByText("TICK 21 · ROLE-VISIBLE TOPOLOGY", { exact: true })).toBeVisible();
  await expect(summary).toContainText("16 / 64 terminals");
  await expect(summary).toContainText("9 queued packets");
  await expect(page.getByRole("combobox", { name: "Domain", exact: true })).toHaveValue("Air");
  await expect(page.locator(".react-flow__edge")).toHaveCount(1);
  await page.getByRole("button", { name: "Fit view", exact: true }).click();
  await expect(page.locator('.react-flow__node[data-id="unit-0"]')).toBeInViewport({ ratio: 0.99 });
  await expect(page.locator('.react-flow__node[data-id="unit-60"]')).toBeInViewport({ ratio: 0.99 });
  await page.screenshot({ path: testInfo.outputPath("network-workspace-scenario.png") });
  expect(errors).toEqual([]);
});
test("starts at the issuing terminal with bounded rendering and preserves access to the full graph", async ({ page }, testInfo) => {
  const dense = denseNetworkProjection();
  const { sockets, errors } = await openWorkspace(page, "unit-0", dense);
  const summary = page.locator('[aria-label="Visible network summary"]');
  await expect(summary).toContainText("64 / 64 terminals");
  await expect(summary).toContainText("126 directional links");
  await expect(summary).toContainText("Connections of Blue unit 1");
  await expect(page.locator(".react-flow__edge")).toHaveCount(126);
  expect(await page.locator("*").count()).toBeLessThan(3_000);
  await page.screenshot({ path: testInfo.outputPath("focused-scenario-network.png") });
  await page.getByRole("button", { name: "All connections", exact: true }).click();
  await expect(summary).toContainText("4032 directional links");
  await expect(page.locator(".react-flow__edge")).toHaveCount(4_032);
  await page.getByRole("button", { name: "My terminal", exact: true }).click();
  await expect(page.locator(".react-flow__edge")).toHaveCount(126);
  dense.tick = 21;
  sockets[0].send(JSON.stringify({ sequence: 21, resync: false, projection: dense }));
  await expect(page.getByText("TICK 21 · ROLE-VISIBLE TOPOLOGY", { exact: true })).toBeVisible();
  await expect(summary).toContainText("Connections of Blue unit 1");
  await expect(page.locator(".react-flow__edge")).toHaveCount(126);
  expect(errors).toEqual([]);
});

test("opening a focused topology retains all role-authorized messages and recovers when the terminal disappears", async ({ page }) => {
  const initial = networkProjection();
  const { sockets, errors } = await openWorkspace(page, "command", initial);
  const summary = page.locator('[aria-label="Visible network summary"]');
  await expect(summary).toContainText("2 / 4 terminals");
  await expect(page.locator(".react-flow__edge")).toHaveCount(2);
  await page.getByRole("tab", { name: /^Messages/ }).click();
  await expect(page.locator(".network-message-list > button")).toHaveCount(3);
  initial.tick = 13;
  initial.nodes = initial.nodes.filter((node) => node.id !== "command");
  initial.links = initial.links.filter((link) => link.from_entity_id !== "command" && link.to_entity_id !== "command");
  sockets[0].send(JSON.stringify({ sequence: 13, resync: false, projection: initial }));
  await expect(summary).toContainText("3 / 3 terminals");
  await expect(page.locator(".react-flow__edge")).toHaveCount(2);
  await expect(page.getByRole("button", { name: "My terminal", exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
});
