[package]
name = "sim-geo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
uom = { version = "0.38", default-features = false, features = ["f64", "si", "std"] }
geo = "0.31"
sha2.workspace = true

[dev-dependencies]
serde_json.workspace = true
